authorizers:
  ZapBuyAuthorizer:
    type: jwt
    identitySource: $request.header.Authorization
    issuerUrl: !GetAtt ZapBuyUserPool.ProviderURL
    audience:
      - !Ref ZapBuyUserPoolClient
cors:
  allowedOrigins: "*"
  allowedMethods:
    - GET
    - POST
    - PUT
    - OPTIONS
  allowedHeaders:
    - Content-Type
    - Authorization
