Resources:
  ZapBuyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: zapbuy-bucket
  ZapBuyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ZapBuyBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${ZapBuyBucket}/*"
